name: Test Knowledge Manager

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: python test_knowledge.py


      - name: Save ai_knowledge.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add utils/ai_knowledge.json
          git commit -m "Create ai knowledge json" || exit 0
          git push